type: google.api.Service
config_version: 3
name: bookstore.endpoints.<MY_PROJECT_ID>.cloud.goog
title: Bookstore gRPC API
apis:
- name: endpoints.examples.bookstore.Bookstore
usage:
  rules:
  - selector: "*"
    allow_unregistered_calls: true

authentication:
  providers:
  - id: google_service_account
    # Replace SERVICE-ACCOUNT-ID with your service account's email address.
    issuer: SERVICE-ACCOUNT-ID
    jwks_uri: https://www.googleapis.com/robot/v1/metadata/x509/SERVICE-ACCOUNT-ID
  rules:
  # This auth rule will apply to all methods.
  - selector: "*"
    requirements:
      - provider_id: google_service_account
