type: google.api.Service
config_version: 3
name: ${_HOSTNAME}
title: Bookstore Server gRPC API
apis:
- name: endpoints.examples.bookstore.Bookstore
usage:
  rules:
  - selector: endpoints.examples.bookstore.Bookstore.ListShelves
    allow_unregistered_calls: true
backend:
  rules:
  - selector: "*"
    address: grpcs://${_HOSTNAME}
